AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example template.

Resources:
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: example.asl.json
      DefinitionSubstitutions:
        MyFunction: !GetAtt MyFunction.Arn

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: where/to/code
      Handler: main.go
      Runtime: go1.x
      Architectures:
        - x86_64

# TODO template.yml and example.asl.json not tested.
