name: Ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('deps.ts') }}
          path: |
            /home/runner/.cache/deno/deps/https

      - name: Deno cache
        run: deno cache deps.ts

      - name: Check format
        run: deno fmt --check

      - name: Test
        run: |
          deno test --coverage=cov
          deno coverage cov --lcov --output=cov.lcov

      - uses: codecov/codecov-action@v3
        with:
          files: ./cov.lcov
